default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: billinho
  password: billinho
  timeout: 5000

development:
  <<: *default
  database: billinhodb
test:
  <<: *default
  database: billinhodb

production:
  <<: *default
  database: billinhodb
