Rails.application.routes.draw do
   get 'institutions/list'
   get 'institutions/new'
   post 'institutions/create'
   patch 'institutions/update'
   get 'institutions/list'
   get 'institutions/show'
   get 'institutions/edit'
   get 'institutions/delete'
   get 'institutions/update'
   get 'institutions/show_kinds'

   get 'students/list'
   get 'students/new'
   post 'students/create'
   patch 'students/update'
   get 'students/list'
   get 'students/show'
   get 'students/edit'
   get 'students/delete'
   get 'students/update'
   get 'students/show_genders'
   get 'students/show_payment_methods'

  root 'application#hello'
end
